import React from 'react';
import {
  Sparkles,
  Bot,
  BrainCircuit,
  FileText,
  Layers,
  CalendarCheck,
  TrendingUp,
  ArrowRight,
  CheckCircle2,
  Star,
  Users,
  Award,
  Zap,
  BookOpen,
  MessageSquare,
  ShieldCheck,
  ChevronRight,
  GraduationCap,
} from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { Logo } from '../common/Logo';

export const LandingPage: React.FC = () => {
  const { setCurrentView, setIsAuthModalOpen, setAuthModalMode } = useApp();

  const handleStartLearning = () => {
    setAuthModalMode('onboarding');
    setIsAuthModalOpen(true);
  };

  const handleLogin = () => {
    setAuthModalMode('login');
    setIsAuthModalOpen(true);
  };

  const handleDirectDashboard = () => {
    setCurrentView('dashboard');
  };

  const features = [
    {
      icon: Bot,
      title: 'AI Tutor',
      desc: 'Ask complex academic questions and get crystal-clear explanations, analogies, step-by-step derivations, and practice questions powered by Gemini.',
      color: 'from-blue-500 to-indigo-600',
      badge: 'Interactive',
    },
    {
      icon: BrainCircuit,
      title: 'Smart Quiz Generator',
      desc: 'Instantly generate customized quizzes by subject, difficulty, and question type with immediate explanations and weak topic detection.',
      color: 'from-violet-500 to-purple-600',
      badge: 'Adaptive',
    },
    {
      icon: FileText,
      title: 'Study Material Summarizer',
      desc: 'Upload class PDFs, handwritten lecture notes, or textbooks to extract high-yield summaries, key definitions, and exam questions.',
      color: 'from-emerald-500 to-teal-600',
      badge: 'Multimodal',
    },
    {
      icon: Layers,
      title: 'AI Flashcards',
      desc: 'Master retention with active-recall flashcard decks generated automatically from your curriculum with spaced repetition memory tips.',
      color: 'from-amber-500 to-orange-600',
      badge: 'Spaced Repetition',
    },
    {
      icon: CalendarCheck,
      title: 'Personalized Study Plans',
      desc: 'Input your exam date and daily study availability to receive an AI-crafted calendar schedule prioritizing your challenging subjects.',
      color: 'from-rose-500 to-pink-600',
      badge: 'Intelligent',
    },
    {
      icon: TrendingUp,
      title: 'Progress Analytics',
      desc: 'Track mastery across all subjects, monitor quiz accuracy trends, analyze learning streaks, and receive automated AI study recommendations.',
      color: 'from-cyan-500 to-blue-600',
      badge: 'Actionable',
    },
  ];

  const steps = [
    {
      num: '01',
      title: 'Choose a Topic',
      desc: 'Select any concept from Mathematics, Physics, Chemistry, Computer Science, or your custom syllabus.',
      icon: BookOpen,
    },
    {
      num: '02',
      title: 'Ask EDUGENIE',
      desc: 'Type or voice-record your question. Choose your learning mode: simple analogy, practice problems, or step-by-step.',
      icon: MessageSquare,
    },
    {
      num: '03',
      title: 'Learn with AI',
      desc: 'Digest tailored explanations generated by Google Gemini with visual breakdowns, formulas, and real-world intuition.',
      icon: Sparkles,
    },
    {
      num: '04',
      title: 'Practice with Quizzes',
      desc: 'Test your understanding immediately with timed adaptive quizzes and discover conceptual gaps before exam day.',
      icon: Zap,
    },
    {
      num: '05',
      title: 'Track Your Progress',
      desc: 'Watch your subject mastery percentages climb, maintain your daily learning streak, and earn gamified badges.',
      icon: Award,
    },
  ];

  const testimonials = [
    {
      name: 'Maya Patel',
      grade: 'Grade 12, STEM Stream',
      quote:
        'EDUGENIE completely changed how I study for physics. The Gemini tutor breaks down difficult rotational dynamics concepts with intuitive analogies that my textbook never managed to convey.',
      rating: 5,
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
    },
    {
      name: 'David Chen',
      grade: 'First-Year CS Major',
      quote:
        'The instant quiz generator and study planner saved my midterms. It automatically diagnosed that I was weak in graph search algorithms and built a 4-day revision schedule that boosted my score to 94%!',
      rating: 5,
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    },
    {
      name: 'Sophia Rodriguez',
      grade: 'AP Biology & Chemistry Student',
      quote:
        'I uploaded my 40-page notes on cellular respiration and EDUGENIE summarized the entire pathway, generated 15 flashcards, and created a practice quiz in less than 30 seconds.',
      rating: 5,
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
    },
  ];

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 flex flex-col font-['Plus_Jakarta_Sans',sans-serif]">
      {/* 1. Header Navigation */}
      <header className="sticky top-0 z-40 bg-white/90 backdrop-blur-md border-b border-slate-200/80">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-20 flex items-center justify-between">
          <Logo size="lg" showTagline onClick={handleDirectDashboard} />

          {/* Center Links */}
          <nav className="hidden md:flex items-center gap-8 text-sm font-semibold text-slate-600">
            <a href="#home" className="hover:text-indigo-600 transition-colors">
              Home
            </a>
            <a href="#features" className="hover:text-indigo-600 transition-colors">
              Features
            </a>
            <a href="#how-it-works" className="hover:text-indigo-600 transition-colors">
              How It Works
            </a>
            <a href="#about" className="hover:text-indigo-600 transition-colors">
              About
            </a>
          </nav>

          {/* Action Buttons */}
          <div className="flex items-center gap-3">
            <button
              onClick={handleLogin}
              className="text-sm font-bold text-slate-700 hover:text-indigo-600 px-4 py-2 rounded-xl hover:bg-slate-100 transition-all"
            >
              Login
            </button>
            <button
              onClick={handleStartLearning}
              className="inline-flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-sm px-5 py-2.5 rounded-xl shadow-md shadow-indigo-600/25 hover:shadow-indigo-600/40 transition-all transform hover:-translate-y-0.5"
            >
              <span>Get Started</span>
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      </header>

      {/* 2. Hero Section */}
      <section id="home" className="relative pt-12 pb-20 lg:pt-20 lg:pb-32 overflow-hidden">
        {/* Background glow effects */}
        <div className="absolute top-1/4 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[700px] h-[400px] bg-gradient-to-tr from-indigo-200/40 via-violet-200/30 to-blue-200/40 rounded-full blur-3xl -z-10" />

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-3xl mx-auto">
            {/* Pill */}
            <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-indigo-50 border border-indigo-200/70 text-indigo-700 text-xs font-bold mb-6 shadow-2xs">
              <Sparkles className="w-4 h-4 text-indigo-600" />
              <span>Powered by Google Gemini 3.8 Flash</span>
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
            </div>

            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-black text-slate-900 tracking-tight leading-[1.15]">
              Your AI-Powered <br className="hidden sm:inline" />
              <span className="bg-gradient-to-r from-indigo-600 via-violet-600 to-purple-600 bg-clip-text text-transparent">
                Personal Learning Assistant
              </span>
            </h1>

            <p className="mt-6 text-lg sm:text-xl text-slate-600 leading-relaxed font-normal">
              EDUGENIE uses Google Gemini AI to make learning personalized, interactive, and easier. From instant concept breakdowns and custom quizzes to automated flashcards and smart study schedules.
            </p>

            {/* CTAs */}
            <div className="mt-8 flex flex-col sm:flex-row items-center justify-center gap-4">
              <button
                onClick={handleStartLearning}
                className="w-full sm:w-auto inline-flex items-center justify-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white font-extrabold text-base px-8 py-3.5 rounded-2xl shadow-lg shadow-indigo-600/30 hover:shadow-indigo-600/50 transition-all transform hover:-translate-y-0.5"
              >
                <span>Start Learning</span>
                <ArrowRight className="w-5 h-5" />
              </button>

              <button
                onClick={handleDirectDashboard}
                className="w-full sm:w-auto inline-flex items-center justify-center gap-2 bg-white hover:bg-slate-50 text-slate-700 border border-slate-300 font-bold text-base px-7 py-3.5 rounded-2xl shadow-xs hover:border-slate-400 transition-all"
              >
                <Zap className="w-4 h-4 text-amber-500" />
                <span>Explore Student Dashboard</span>
              </button>
            </div>

            {/* Value bullets */}
            <div className="mt-8 flex flex-wrap items-center justify-center gap-6 text-xs sm:text-sm font-semibold text-slate-500">
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                <span>No Credit Card Needed</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                <span>Curriculum-Aligned AI</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                <span>Real-Time Feedback</span>
              </div>
            </div>
          </div>

          {/* Hero Visual Mockup */}
          <div className="mt-14 relative max-w-5xl mx-auto">
            <div className="rounded-3xl p-2 bg-gradient-to-b from-indigo-500/20 via-slate-200/40 to-slate-200/80 shadow-2xl">
              <div className="bg-white rounded-2xl border border-slate-200/80 overflow-hidden shadow-lg">
                {/* Browser bar */}
                <div className="bg-slate-100/90 px-4 py-3 border-b border-slate-200/80 flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <div className="w-3 h-3 rounded-full bg-rose-400" />
                    <div className="w-3 h-3 rounded-full bg-amber-400" />
                    <div className="w-3 h-3 rounded-full bg-emerald-400" />
                    <span className="ml-3 text-xs font-medium text-slate-400">
                      https://edugenie.app/student/alex/tutor
                    </span>
                  </div>
                  <div className="flex items-center gap-2 text-xs font-semibold text-indigo-700 bg-indigo-50 px-2.5 py-1 rounded-md">
                    <Sparkles className="w-3 h-3" />
                    <span>Gemini 3.8 Active</span>
                  </div>
                </div>

                {/* Dashboard Snapshot Grid */}
                <div className="p-6 grid grid-cols-1 md:grid-cols-3 gap-6 bg-slate-50/50">
                  {/* Left Column: AI Tutor Chat Preview */}
                  <div className="md:col-span-2 bg-white rounded-2xl p-5 border border-slate-200 shadow-xs space-y-4">
                    <div className="flex items-center justify-between pb-3 border-b border-slate-100">
                      <div className="flex items-center gap-3">
                        <div className="w-9 h-9 rounded-xl bg-indigo-600 text-white flex items-center justify-center font-bold">
                          EG
                        </div>
                        <div>
                          <h4 className="text-sm font-bold text-slate-800">Ask EDUGENIE</h4>
                          <p className="text-[11px] text-slate-500">Photosynthesis in Simple Terms</p>
                        </div>
                      </div>
                      <span className="text-[11px] font-semibold text-emerald-600 bg-emerald-50 px-2 py-0.5 rounded-full border border-emerald-200">
                        Concept Mastered
                      </span>
                    </div>

                    {/* Chat Bubble */}
                    <div className="space-y-3">
                      <div className="flex justify-end">
                        <div className="bg-indigo-600 text-white rounded-2xl rounded-tr-xs px-4 py-2 text-xs font-medium max-w-md shadow-xs">
                          Explain photosynthesis simply and give me a formula!
                        </div>
                      </div>

                      <div className="flex items-start gap-3">
                        <div className="w-7 h-7 rounded-lg bg-indigo-100 text-indigo-700 flex items-center justify-center text-xs font-bold shrink-0 mt-1">
                          ✨
                        </div>
                        <div className="bg-slate-50 border border-slate-200/70 rounded-2xl rounded-tl-xs p-4 text-xs text-slate-700 space-y-2 max-w-lg">
                          <p className="font-semibold text-slate-900">
                            🌱 Think of Photosynthesis as Nature's Solar Kitchen:
                          </p>
                          <p className="text-slate-600">
                            Plants trap sunlight with green chlorophyll inside chloroplasts, take water from the roots and $CO_2$ from the air, and cook up high-energy glucose sugar while venting fresh oxygen!
                          </p>
                          <div className="p-2.5 rounded-xl bg-white border border-indigo-100 font-mono text-[11px] text-indigo-900">
                            6CO₂ + 6H₂O + Sunlight → C₆H₁₂O₆ + 6O₂
                          </div>
                          <div className="flex items-center gap-2 pt-1">
                            <span className="text-[10px] bg-indigo-50 text-indigo-700 px-2 py-0.5 rounded font-semibold">
                              💡 Real-World Analogy
                            </span>
                            <span className="text-[10px] bg-purple-50 text-purple-700 px-2 py-0.5 rounded font-semibold">
                              🎯 Exam Takeaway
                            </span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Right Column: Live Statistics & Streak Preview */}
                  <div className="space-y-4">
                    <div className="bg-white rounded-2xl p-4 border border-slate-200 shadow-xs">
                      <div className="flex items-center justify-between mb-2">
                        <span className="text-xs font-bold text-slate-500 uppercase">Learning Streak</span>
                        <span className="text-xs font-extrabold text-amber-600 bg-amber-50 px-2 py-0.5 rounded-full border border-amber-200 flex items-center gap-1">
                          🔥 7 Days
                        </span>
                      </div>
                      <div className="text-2xl font-black text-slate-900">42 Topics</div>
                      <div className="text-[11px] text-slate-500 mt-1">
                        Completed this month across 4 subjects
                      </div>
                      <div className="w-full bg-slate-100 rounded-full h-2 mt-3 overflow-hidden">
                        <div className="bg-indigo-600 h-2 rounded-full w-4/5" />
                      </div>
                    </div>

                    <div className="bg-white rounded-2xl p-4 border border-slate-200 shadow-xs">
                      <span className="text-xs font-bold text-slate-500 uppercase">Upcoming Study Task</span>
                      <div className="mt-2 p-2.5 rounded-xl bg-indigo-50/60 border border-indigo-100">
                        <div className="text-xs font-bold text-indigo-950">Physics: Rotational Dynamics</div>
                        <div className="text-[11px] text-indigo-600 mt-0.5">Today • 40 min • Practice Problems</div>
                      </div>
                      <button
                        onClick={handleDirectDashboard}
                        className="mt-3 w-full py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl text-xs font-bold shadow-xs transition-colors"
                      >
                        Launch Interactive Session
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 3. Features Section */}
      <section id="features" className="py-20 bg-white border-y border-slate-200/80">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-3xl mx-auto mb-16">
            <span className="text-xs font-extrabold uppercase tracking-widest text-indigo-600 bg-indigo-50 px-3 py-1 rounded-full border border-indigo-200/80">
              Powerful Learning Features
            </span>
            <h2 className="mt-4 text-3xl sm:text-4xl font-black text-slate-900 tracking-tight">
              Everything You Need to Ace Your Classes
            </h2>
            <p className="mt-4 text-base sm:text-lg text-slate-600">
              Built ground-up with Google Gemini AI to transform dry textbooks into dynamic, engaging, and memorable learning journeys.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feat, idx) => {
              const Icon = feat.icon;
              return (
                <div
                  key={idx}
                  className="rounded-2xl p-6 bg-slate-50/60 hover:bg-white border border-slate-200/80 hover:border-indigo-200 hover:shadow-xl transition-all duration-300 group flex flex-col justify-between"
                >
                  <div>
                    <div className="flex items-center justify-between mb-5">
                      <div
                        className={`w-12 h-12 rounded-xl bg-gradient-to-tr ${feat.color} text-white flex items-center justify-center shadow-md group-hover:scale-110 transition-transform`}
                      >
                        <Icon className="w-6 h-6" />
                      </div>
                      <span className="text-[11px] font-bold uppercase tracking-wider text-slate-500 bg-white border border-slate-200 px-2 py-0.5 rounded-md">
                        {feat.badge}
                      </span>
                    </div>

                    <h3 className="text-xl font-bold text-slate-900 group-hover:text-indigo-600 transition-colors">
                      {feat.title}
                    </h3>
                    <p className="mt-3 text-sm text-slate-600 leading-relaxed">{feat.desc}</p>
                  </div>

                  <div className="mt-6 pt-4 border-t border-slate-200/60 flex items-center text-xs font-bold text-indigo-600 group-hover:text-indigo-700">
                    <span>Try Feature in App</span>
                    <ChevronRight className="w-4 h-4 ml-1 group-hover:translate-x-1 transition-transform" />
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* 4. How EDUGENIE Works */}
      <section id="how-it-works" className="py-20 bg-slate-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-3xl mx-auto mb-16">
            <span className="text-xs font-extrabold uppercase tracking-widest text-violet-600 bg-violet-50 px-3 py-1 rounded-full border border-violet-200/80">
              The 5-Step Learning Loop
            </span>
            <h2 className="mt-4 text-3xl sm:text-4xl font-black text-slate-900 tracking-tight">
              How EDUGENIE Works
            </h2>
            <p className="mt-4 text-base sm:text-lg text-slate-600">
              Follow our scientifically proven active-learning loop designed to maximize retention while cutting study time in half.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-5 gap-6">
            {steps.map((step, idx) => {
              const StepIcon = step.icon;
              return (
                <div
                  key={idx}
                  className="bg-white rounded-2xl p-6 border border-slate-200/80 shadow-xs relative flex flex-col justify-between"
                >
                  <div className="text-3xl font-black text-slate-200 mb-3">{step.num}</div>
                  <div className="w-10 h-10 rounded-xl bg-indigo-50 text-indigo-600 flex items-center justify-center mb-4">
                    <StepIcon className="w-5 h-5" />
                  </div>
                  <h4 className="text-base font-bold text-slate-900 mb-2">{step.title}</h4>
                  <p className="text-xs text-slate-600 leading-relaxed">{step.desc}</p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* 5. Testimonials */}
      <section className="py-20 bg-white border-t border-slate-200/80">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-3xl mx-auto mb-16">
            <span className="text-xs font-extrabold uppercase tracking-widest text-amber-600 bg-amber-50 px-3 py-1 rounded-full border border-amber-200/80">
              Student Stories
            </span>
            <h2 className="mt-4 text-3xl sm:text-4xl font-black text-slate-900 tracking-tight">
              Loved by Students Everywhere
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {testimonials.map((t, idx) => (
              <div
                key={idx}
                className="rounded-2xl p-6 bg-slate-50/80 border border-slate-200/80 flex flex-col justify-between shadow-xs"
              >
                <div>
                  <div className="flex items-center gap-1 text-amber-400 mb-4">
                    {[...Array(t.rating)].map((_, i) => (
                      <Star key={i} className="w-4 h-4 fill-amber-400" />
                    ))}
                  </div>
                  <p className="text-sm text-slate-700 italic leading-relaxed">
                    "{t.quote}"
                  </p>
                </div>

                <div className="mt-6 pt-4 border-t border-slate-200 flex items-center gap-3">
                  <img
                    src={t.avatar}
                    alt={t.name}
                    className="w-10 h-10 rounded-full object-cover border border-slate-200"
                  />
                  <div>
                    <h5 className="text-sm font-bold text-slate-900">{t.name}</h5>
                    <p className="text-xs text-slate-500">{t.grade}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* 6. Call To Action Banner */}
      <section className="py-16 bg-gradient-to-br from-indigo-900 via-indigo-800 to-violet-900 text-white relative overflow-hidden">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 text-center relative z-10">
          <GraduationCap className="w-12 h-12 text-indigo-300 mx-auto mb-4" />
          <h2 className="text-3xl sm:text-4xl font-black tracking-tight">
            Ready to Learn Smarter and Learn Faster?
          </h2>
          <p className="mt-4 text-base sm:text-lg text-indigo-200 max-w-2xl mx-auto">
            Join thousands of high school and university students preparing for exams with EDUGENIE and Google Gemini.
          </p>

          <div className="mt-8 flex flex-col sm:flex-row items-center justify-center gap-4">
            <button
              onClick={handleStartLearning}
              className="w-full sm:w-auto inline-flex items-center justify-center gap-2 bg-white text-indigo-900 hover:bg-indigo-50 font-black text-base px-8 py-3.5 rounded-2xl shadow-xl transition-all transform hover:-translate-y-0.5"
            >
              <span>Get Started Now</span>
              <ArrowRight className="w-5 h-5 text-indigo-900" />
            </button>
            <button
              onClick={handleDirectDashboard}
              className="w-full sm:w-auto inline-flex items-center justify-center gap-2 bg-indigo-700/60 hover:bg-indigo-700 text-white border border-indigo-500/50 font-bold text-base px-7 py-3.5 rounded-2xl transition-all"
            >
              <span>Open Alex's Demo Dashboard</span>
            </button>
          </div>
        </div>
      </section>

      {/* 7. Footer */}
      <footer id="about" className="bg-slate-900 text-slate-400 py-12 border-t border-slate-800 text-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 grid grid-cols-1 md:grid-cols-4 gap-8">
          <div className="space-y-4 md:col-span-2">
            <Logo size="md" className="brightness-125" />
            <p className="text-slate-400 max-w-sm text-xs leading-relaxed">
              EDUGENIE is an AI-powered personal learning assistant designed for students to master concepts, practice quizzes, and stay organized. Powered by Google Gemini 3.8 Flash.
            </p>
            <div className="text-xs text-slate-500">
              © {new Date().getFullYear()} EDUGENIE. All rights reserved. Built with Google AI Studio.
            </div>
          </div>

          <div>
            <h5 className="text-white font-bold text-xs uppercase tracking-wider mb-3">Product</h5>
            <ul className="space-y-2 text-xs">
              <li>
                <button onClick={() => setCurrentView('tutor')} className="hover:text-white transition-colors">
                  AI Tutor
                </button>
              </li>
              <li>
                <button onClick={() => setCurrentView('quiz')} className="hover:text-white transition-colors">
                  Smart Quiz Generator
                </button>
              </li>
              <li>
                <button onClick={() => setCurrentView('materials')} className="hover:text-white transition-colors">
                  Study Material Analyzer
                </button>
              </li>
              <li>
                <button onClick={() => setCurrentView('flashcards')} className="hover:text-white transition-colors">
                  AI Flashcards
                </button>
              </li>
              <li>
                <button onClick={() => setCurrentView('planner')} className="hover:text-white transition-colors">
                  Study Planner
                </button>
              </li>
            </ul>
          </div>

          <div>
            <h5 className="text-white font-bold text-xs uppercase tracking-wider mb-3">Technology</h5>
            <ul className="space-y-2 text-xs">
              <li className="flex items-center gap-1.5 text-emerald-400 font-semibold">
                <Sparkles className="w-3.5 h-3.5" />
                Google Gemini API
              </li>
              <li>Firebase Firestore Ready</li>
              <li>Spaced Repetition Engine</li>
              <li>Adaptive Question Bank</li>
            </ul>
          </div>
        </div>
      </footer>
    </div>
  );
};
