import React, { useState } from 'react';
import {
  Sparkles,
  Layers,
  RotateCw,
  CheckCircle2,
  XCircle,
  ChevronLeft,
  ChevronRight,
  Plus,
  BookOpen,
  Award,
  Zap,
} from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { apiService } from '../../services/api';
import { Flashcard } from '../../types';

export const FlashcardDeck: React.FC = () => {
  const { flashcards, addFlashcards, markFlashcardStatus, profile, triggerConfetti } = useApp();

  const [currentIndex, setCurrentIndex] = useState(0);
  const [isFlipped, setIsFlipped] = useState(false);
  const [selectedSubject, setSelectedSubject] = useState<string>('All');
  const [newTopicInput, setNewTopicInput] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [isGeneratorOpen, setIsGeneratorOpen] = useState(false);

  // Filter cards by subject
  const filteredCards =
    selectedSubject === 'All'
      ? flashcards
      : flashcards.filter((c) => c.subject.toLowerCase() === selectedSubject.toLowerCase());

  const currentCard: Flashcard | undefined = filteredCards[currentIndex];

  const handleFlip = () => {
    setIsFlipped(!isFlipped);
  };

  const handleNext = () => {
    if (currentIndex < filteredCards.length - 1) {
      setCurrentIndex((prev) => prev + 1);
      setIsFlipped(false);
    }
  };

  const handlePrev = () => {
    if (currentIndex > 0) {
      setCurrentIndex((prev) => prev - 1);
      setIsFlipped(false);
    }
  };

  const handleMarkMastered = () => {
    if (!currentCard) return;
    markFlashcardStatus(currentCard.id, 'mastered');
    triggerConfetti();
    handleNext();
  };

  const handleMarkNeedPractice = () => {
    if (!currentCard) return;
    markFlashcardStatus(currentCard.id, 'learning');
    handleNext();
  };

  const handleGenerateCards = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTopicInput.trim()) return;

    setIsGenerating(true);
    try {
      const response = await apiService.generateFlashcards(
        newTopicInput.trim(),
        selectedSubject === 'All' ? 'Science' : selectedSubject,
        6
      );

      if (response.flashcards && response.flashcards.length > 0) {
        addFlashcards(response.flashcards);
        triggerConfetti();
        setIsGeneratorOpen(false);
        setNewTopicInput('');
        setCurrentIndex(0);
        setIsFlipped(false);
      }
    } catch (e) {
      alert('Failed to generate flashcards. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  const masteredCount = filteredCards.filter((c) => c.status === 'mastered').length;
  const masteryPercentage =
    filteredCards.length > 0 ? Math.round((masteredCount / filteredCards.length) * 100) : 0;

  return (
    <div className="max-w-4xl mx-auto space-y-8 pb-12">
      {/* Header */}
      <div className="bg-white rounded-3xl p-6 sm:p-8 border border-slate-200/90 shadow-xs flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 rounded-2xl bg-gradient-to-tr from-amber-500 to-orange-600 text-white flex items-center justify-center shadow-md shadow-amber-500/25">
            <Layers className="w-6 h-6" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h1 className="text-2xl font-black text-slate-900 tracking-tight">AI Flashcards</h1>
              <span className="text-[10px] font-bold uppercase bg-amber-50 text-amber-700 px-2 py-0.5 rounded-full border border-amber-200">
                Spaced Repetition
              </span>
            </div>
            <p className="text-xs sm:text-sm text-slate-500">
              Active recall cards dynamically generated by Google Gemini to supercharge memory retention.
            </p>
          </div>
        </div>

        <button
          onClick={() => setIsGeneratorOpen(!isGeneratorOpen)}
          className="px-4 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white font-extrabold text-xs flex items-center gap-2 shadow-md shadow-indigo-600/20 transition-all shrink-0"
        >
          <Sparkles className="w-4 h-4" />
          <span>Generate New Deck</span>
        </button>
      </div>

      {/* Generator Drawer if open */}
      {isGeneratorOpen && (
        <div className="bg-gradient-to-br from-indigo-50 to-purple-50 rounded-3xl p-6 border border-indigo-200 shadow-sm animate-in fade-in">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-sm font-black text-slate-900 flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-indigo-600" />
              <span>Generate AI Flashcards with Gemini</span>
            </h3>
            <button
              onClick={() => setIsGeneratorOpen(false)}
              className="text-xs font-bold text-slate-400 hover:text-slate-600"
            >
              Cancel
            </button>
          </div>

          <form onSubmit={handleGenerateCards} className="flex flex-col sm:flex-row gap-3">
            <input
              type="text"
              value={newTopicInput}
              onChange={(e) => setNewTopicInput(e.target.value)}
              placeholder="Enter any topic: 'Newton's Laws', 'Calculus Derivatives', 'Organic Mechanisms'..."
              required
              className="flex-1 px-4 py-3 text-xs sm:text-sm rounded-xl border border-slate-200 bg-white focus:border-indigo-600 outline-none font-medium"
            />
            <button
              type="submit"
              disabled={isGenerating}
              className="px-6 py-3 bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-xs rounded-xl shadow-md transition-all shrink-0"
            >
              {isGenerating ? 'Generating 6 Cards...' : 'Create Deck'}
            </button>
          </form>
        </div>
      )}

      {/* Subject Filter Pills & Mastery Stats */}
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div className="flex items-center gap-2 overflow-x-auto no-scrollbar py-1">
          {['All', ...profile.subjects].map((sub) => (
            <button
              key={sub}
              onClick={() => {
                setSelectedSubject(sub);
                setCurrentIndex(0);
                setIsFlipped(false);
              }}
              className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-all border ${
                selectedSubject === sub
                  ? 'bg-slate-900 text-white border-slate-900 shadow-xs'
                  : 'bg-white text-slate-600 border-slate-200 hover:bg-slate-50'
              }`}
            >
              {sub}
            </button>
          ))}
        </div>

        <div className="flex items-center gap-3 text-xs font-bold text-slate-700 bg-white px-3.5 py-1.5 rounded-xl border border-slate-200 shadow-2xs">
          <span>Mastery: {masteryPercentage}%</span>
          <div className="w-20 bg-slate-100 rounded-full h-2 overflow-hidden">
            <div
              className="bg-emerald-500 h-2 rounded-full transition-all duration-500"
              style={{ width: `${masteryPercentage}%` }}
            />
          </div>
          <span className="text-slate-400">
            ({masteredCount}/{filteredCards.length})
          </span>
        </div>
      </div>

      {/* 3D Flip Flashcard Main Canvas */}
      {currentCard ? (
        <div className="space-y-6">
          <div className="flex items-center justify-between text-xs font-bold text-slate-400 px-2">
            <span>
              Card {currentIndex + 1} of {filteredCards.length}
            </span>
            <span className="uppercase text-[11px] tracking-wider text-indigo-600 bg-indigo-50 px-2 py-0.5 rounded">
              {currentCard.subject}
            </span>
          </div>

          {/* Interactive Flip Card Container */}
          <div
            onClick={handleFlip}
            className="w-full min-h-[300px] sm:min-h-[340px] cursor-pointer perspective-1000 select-none group"
          >
            <div
              className={`relative w-full h-full min-h-[300px] sm:min-h-[340px] rounded-3xl transition-transform duration-500 transform-style-3d border shadow-lg ${
                isFlipped
                  ? 'rotate-y-180 bg-gradient-to-br from-indigo-950 to-slate-900 text-white border-indigo-900'
                  : 'bg-white text-slate-900 border-slate-200/90 hover:border-indigo-300'
              }`}
            >
              {/* Front Side */}
              <div
                className={`absolute inset-0 p-8 flex flex-col justify-between backface-hidden ${
                  isFlipped ? 'hidden' : 'flex'
                }`}
              >
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold uppercase tracking-wider text-slate-400">
                    Question / Concept
                  </span>
                  <div className="flex items-center gap-1.5 text-xs text-indigo-600 font-semibold">
                    <RotateCw className="w-3.5 h-3.5" />
                    <span>Click to reveal answer</span>
                  </div>
                </div>

                <div className="my-auto text-center px-4">
                  <h3 className="text-xl sm:text-2xl font-black text-slate-900 leading-relaxed">
                    {currentCard.front}
                  </h3>
                </div>

                <div className="flex items-center justify-between pt-4 border-t border-slate-100 text-xs text-slate-400">
                  <span>Difficulty: {currentCard.difficulty || 'Medium'}</span>
                  <span className="text-indigo-600 font-bold">EDUGENIE Flashcards</span>
                </div>
              </div>

              {/* Back Side */}
              <div
                className={`absolute inset-0 p-8 flex flex-col justify-between backface-hidden rotate-y-180 ${
                  isFlipped ? 'flex' : 'hidden'
                }`}
              >
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold uppercase tracking-wider text-indigo-300">
                    Answer / Explanation
                  </span>
                  <span className="text-xs text-slate-400">Click to flip back</span>
                </div>

                <div className="my-auto text-center px-4 space-y-4">
                  <p className="text-base sm:text-lg font-bold text-indigo-50 leading-relaxed">
                    {currentCard.back}
                  </p>

                  {currentCard.memoryTip && (
                    <div className="inline-block p-3 rounded-2xl bg-white/10 border border-white/10 text-xs text-amber-200 font-medium max-w-lg">
                      💡 <strong>Memory Tip:</strong> {currentCard.memoryTip}
                    </div>
                  )}
                </div>

                <div className="flex items-center justify-between pt-4 border-t border-white/10 text-xs text-indigo-300">
                  <span>Gemini Verified</span>
                  <span>Active Recall Technique</span>
                </div>
              </div>
            </div>
          </div>

          {/* Action Buttons: Mastery & Navigation */}
          <div className="flex flex-col sm:flex-row items-center justify-between gap-4 pt-2">
            {/* Prev / Next */}
            <div className="flex items-center gap-2">
              <button
                onClick={handlePrev}
                disabled={currentIndex === 0}
                className="p-3 rounded-xl border border-slate-200 bg-white hover:bg-slate-50 disabled:opacity-40 font-bold text-xs text-slate-700 transition-colors shadow-2xs"
              >
                <ChevronLeft className="w-4 h-4" />
              </button>
              <button
                onClick={handleNext}
                disabled={currentIndex === filteredCards.length - 1}
                className="p-3 rounded-xl border border-slate-200 bg-white hover:bg-slate-50 disabled:opacity-40 font-bold text-xs text-slate-700 transition-colors shadow-2xs"
              >
                <ChevronRight className="w-4 h-4" />
              </button>
            </div>

            {/* Known vs Need Practice */}
            <div className="flex items-center gap-3 w-full sm:w-auto">
              <button
                onClick={handleMarkNeedPractice}
                className="flex-1 sm:flex-none px-5 py-3 rounded-xl border border-rose-200 bg-rose-50 hover:bg-rose-100 text-rose-700 font-bold text-xs flex items-center justify-center gap-2 transition-colors"
              >
                <XCircle className="w-4 h-4" />
                <span>Need Practice</span>
              </button>

              <button
                onClick={handleMarkMastered}
                className="flex-1 sm:flex-none px-6 py-3 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-black text-xs flex items-center justify-center gap-2 shadow-md shadow-emerald-600/20 transition-all"
              >
                <CheckCircle2 className="w-4 h-4" />
                <span>I Know This!</span>
              </button>
            </div>
          </div>
        </div>
      ) : (
        <div className="bg-white rounded-3xl p-12 text-center border border-slate-200/90 shadow-xs space-y-3">
          <Layers className="w-12 h-12 text-slate-300 mx-auto" />
          <h3 className="text-base font-bold text-slate-700">No flashcards in this category</h3>
          <p className="text-xs text-slate-500">
            Use the "Generate New Deck" button above to ask Gemini to generate cards for your syllabus!
          </p>
        </div>
      )}
    </div>
  );
};
